replicaCount: 3
image:
  repository: nashpaz123/pizza-app
  tag: latest #in prod this would be set to a valid tag that went through pipeline tests
resources:
  limits:
    cpu: "500m"
    memory: "512Mi"
  requests:
    cpu: "200m"
    memory: "256Mi"

#TODO: secrets, ssl, ingress, networkPolicy
ingress:
  enabled: false
  annotations: {}

  labels: {}

  hosts: []
      # - pizza.domain.com

  tls: []
    # - secretName: pizza-general-tls
    #   hosts:
    #   - pizza.example.com

secret:
  annotations: {}
